image: node:16.17.0

pipelines:
  branches:
    master:
      - step:
          caches:
            - node
          name: "Build and Deploy on Prod"
          deployment: Prod-Build
          script:
            - npm install mui
            - npm install --save mui-date-picker
            - CI=false
            - npm run build
            - ls -ltr
            - cd build
            - pipe: atlassian/aws-s3-deploy:0.2.4
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                COMMAND: "deploy-only"
                DEBUG: "true"
                ACL: "public-read"
                S3_BUCKET: $S3_BUCKET
                LOCAL_PATH: $(pwd)
      - step:
          name: "Invalidating cache on Cloudfront"
          deployment: Prod-Deploy
          script:
            - pipe: "atlassian/aws-cloudfront-invalidate:0.1.2"
              variables:
                AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                AWS_DEFAULT_REGION: $AWS_DEFAULT_REGION
                AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                DISTRIBUTION_ID: $DISTRIBUTION_ID
          size: 2x
